apiVersion: v1
kind: Secret
metadata:
  name: printer-agent-secret
  namespace: universal-print
  labels:
    app: printer-agent-worker
type: Opaque
stringData:
  # K8S stringData will auto-convert these raw strings to secure base64 secret values on creation
  ApiSettings__ApiKey: "up_sec_live_9108a73bcde02f"
  ApiSettings__BearerToken: "YOUR_BEARER_TOKEN_HERE"
