---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: harbor-auth
  namespace: universal-print
spec:
  encryptedData:
    .dockerconfigjson: AgDa/WWc6OVWYbx/si8RNvGZt8ug76jfm1oiprB4qE0F6xlAd59VARGdpAbJQ5W1Gg1HPtgAwQ2I+P8OFmfOxZM+u2hfJgqDLQQHe2mo10Jml926qoLSP76Z1iynBMtq+pxZ9gI8pJDKR959vshVFau+lHZUjgn0szeLTvkT7kDrH0YqGNU5RNNjd7Cgh8buqgOLldm9G6jWfeik+8pvdK3FiDb78irn4B0OLdpwYskkgI5LjJdhTsfdQ1lt/K+QELOzBwm4khw3ZZd4STkMFLNUHW1RmzgVSOR2lrh59ekoG20+KJRmQLerrYikX/KlOEPEMGGF2KW7JCgertq0KPiQxozsLf/P2VDgjwC7kYNkme7o+J3r5OrMJ9MAs1tfsOXnDdmOfSQgsO9GGxgb/5TxvC7oOfqK4ODIHpvVGSeXjxUleD6PP1DGPtztj400gruW1Co5fM0IfZ2Yhrtxpi7U38lV1n5/XR0cRllDvuC1p1tDjoPOlfP0smVjTw67aO/l7cmPJ7I8OFGtZQgyUGuNRgqsGqQWVmLpQxLyA42i3BQvh2L2ZgeiGeSsCiJnati32RHI9YmWXHdqEhDdYbtgj8YS/yWdcTan+LeKKt4oZl7HeqDrIl2uPW4fonV2ilQYvS+j1CekKXDALWh5F/+JVUl/O9G5bJcXaqOr/X3DjyxhU/9iXRlhGP2Ck6dhDz5Emraqa5FBK4PrpDR7Tn3ZaSk2aGIalmVUfPN3RZ3PXbqJMaDvurQi0UirHoM6jZ+xyiMd8+lNob7RO7fQ2ZgX8GJjT/a7jRmgeXsd5ZoF6Ebhgr20fvTJMZLAdmZVHJJT1oQAvoJFdHc6m39ly1LPuQ2yAkoN+sLtjWNKHI6RV8VzWyvhPGxoP3YZuzj6eRV4WG1KcfiCgGlqxzqGhcV3oL1zUY/j/xyN67ZeYqpcuZRKavTgJtERZW3N2CP79XQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: harbor-auth
      namespace: universal-print
    type: kubernetes.io/dockerconfigjson
